# Generated by Django 4.0.6 on 2022-07-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobstatus'),
        ),
    ]
